package net.simforge.airways.processes.transportflight.event;

/**
 * This event is generated by Pilot. TransportFlight reacts and does its job - board passengers.
 */
public class BoardingStarted {
}
